spring.application.name=scada-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/scada
spring.datasource.username=rikkicasupanan
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true